env:
  browser: true
  es2020: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'eslint-config-prettier'
  - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - prettier
  - "@typescript-eslint"
rules: {
  prettier/prettier: error,
  semi: warn,
  curly: warn,
  brace-style: 1,
  indent: ["warn", 2, {"SwitchCase":1}]
}
