---
env:
  jquery: true
  browser: true
  es2020: true
extends:
  - 'eslint:recommended'
  - 'eslint-config-prettier'
  - 'plugin:prettier/recommended'
  - '@typhonjs-fvtt/eslint-config-foundry.js'

parserOptions:
  ecmaVersion: 2020
  sourceType: module
  tsconfigRootDir: .
plugins:
  - prettier
rules:
  #Fvtt support
  no-shadow: off

  #Personal preferences
  prettier/prettier: error
  semi: warn
  curly: warn
  brace-style: 1
  indent: [ "warn", 2, { "SwitchCase": 1 } ]
  'no-trailing-spaces': [ "error" ]
  'eol-last': [ "error", "always" ]
  'key-spacing': [ "error" ]
