pull_request_rules:
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}

  - name: remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews: {}

  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request is now in conflicts. Could you fix it? 🙏

  - name: ask to fix commit message
    conditions:
      - status-failure=Semantic Pull Request
      - -closed
    actions:
      comment:
        message: |
          Title does not follow the guidelines of [Conventional Commits](https://www.conventionalcommits.org).
          Please adjust title before merge.
