---
singleQuote: true
requirePragma: true
tabWidth: 2
overrides:
  - files:
      - "*.scss"
      - "*.css"
    options:
      requirePragma: false
      parser: scss
  - files: "*.html"
    options:
      requirePragma: true
      parser: html
      htmlWhitespaceSensitivity: ignore
