§ignoredBuiltDependencies:
  - '@parcel/watcher'
  - postinstall-postinstall
  - classic-level
  - '@league-of-foundry-developers/foundry-vtt-types'
onlyBuiltDependencies:
  - esbuild
blockExoticSubdeps: true
minimumReleaseAge: 4320
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080
peerDependencyRules:
  ignoreMissing:
    - "@pixi/compressed-textures"
    - "@pixi/particle-emitter"
  allowedVersions:
    "@pixi/basis>@pixi/core": "*"
    "@pixi/basis>@pixi/assets": "*"
