blockExoticSubdeps: true
ignoredBuiltDependencies:
  - classic-level
  - '@league-of-foundry-developers/foundry-vtt-types'
  - '@parcel/watcher'
  - postinstall-postinstall
minimumReleaseAge: 4320
onlyBuiltDependencies:
  - esbuild
peerDependencyRules:
  allowedVersions:
    "@pixi/basis>@pixi/assets": "*"
    "@pixi/basis>@pixi/core": "*"
  ignoreMissing:
    - "@pixi/compressed-textures"
    - "@pixi/particle-emitter"
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080
